# Generated by Django 3.1.4 on 2020-12-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddrive',
            name='donate_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
        migrations.AddField(
            model_name='donor',
            name='donated_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
        migrations.AlterField(
            model_name='blooddrive',
            name='drive_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_owner', to='hospital.hospital'),
        ),
    ]
