# Generated by Django 3.1.4 on 2020-12-08 15:31

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('hospital_name', models.CharField(max_length=400)),
                ('capacity_required', models.IntegerField(default=0)),
                ('capacity_available', models.IntegerField(default=0)),
                ('adminstrator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_age', models.IntegerField(default=0)),
                ('blood_type', models.CharField(max_length=5)),
                ('blood_status', models.TextField(max_length=60)),
                ('quantity_donated', models.IntegerField(default=0)),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BloodDrive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_title', models.CharField(max_length=150)),
                ('drive_location', models.TextField(max_length=255)),
                ('drive_date', models.DateTimeField(auto_now_add=True)),
                ('capacity_collected', models.IntegerField(default=0)),
                ('donors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.donor')),
                ('drive_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
    ]
