# Generated by Django 3.1.4 on 2020-12-10 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_drive_donate_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='donated_blood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.donor'),
        ),
    ]
