# Generated by Django 3.1.4 on 2020-12-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_drive_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='drive_date',
        ),
        migrations.AddField(
            model_name='drive',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
