# Generated by Django 3.1.4 on 2020-12-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20201209_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='donor_name',
        ),
        migrations.AddField(
            model_name='donor',
            name='donor_first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='donor',
            name='donor_last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
