# Generated by Django 3.1.4 on 2020-12-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_hospital_donated_blood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='donated_to',
        ),
        migrations.AddField(
            model_name='donor',
            name='donated_to',
            field=models.ManyToManyField(blank=True, null=True, to='hospital.Hospital'),
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='donated_blood',
        ),
        migrations.AddField(
            model_name='hospital',
            name='donated_blood',
            field=models.ManyToManyField(blank=True, null=True, to='hospital.Donor'),
        ),
    ]
