# Generated by Django 3.1.4 on 2020-12-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20201209_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
