# Generated by Django 3.1.4 on 2020-12-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20201210_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='donated_blood',
            field=models.ManyToManyField(blank=True, null=True, related_name='donated_blood', to='hospital.Donor'),
        ),
    ]
