# Generated by Django 3.1.4 on 2020-12-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_blooddrive_donate_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddrive',
            name='donors',
        ),
        migrations.RemoveField(
            model_name='blooddrive',
            name='drive_owner',
        ),
    ]
