# Generated by Django 3.1.4 on 2020-12-10 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20201210_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drive',
            name='donate_to',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='donated_blood',
        ),
        migrations.AddField(
            model_name='drive',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donated_to',
            field=models.ManyToManyField(blank=True, to='hospital.Drive'),
        ),
    ]
