# Generated by Django 3.1.4 on 2020-12-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20201209_1705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BloodDrive',
            new_name='Drive',
        ),
    ]
