# Generated by Django 3.1.4 on 2020-12-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20201210_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donated_to',
            field=models.ManyToManyField(blank=True, related_name='drive', to='hospital.Drive'),
        ),
    ]
