# Generated by Django 3.1.4 on 2020-12-10 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_auto_20201210_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='donated_to',
        ),
        migrations.AddField(
            model_name='donor',
            name='donated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive', to='hospital.drive'),
        ),
    ]
